[workspace]
default-members = ["flatrun", "flatrun-host"]
members = [
    "flatrun",
    "flatrun-host"
]
resolver = "2"

[workspace.dependencies]
clap = { version = "4.5.4", features = ["derive"] }
env_logger = "0.11.3"
libflatpak = "0.5.0"
log = "0.4.21"