# Generated by rust2rpm 26
%bcond_without check

%global ver ###
%global commit ###
%global date ###

# prevent library files from being installed
%global cargo_install_lib 0

Name:           portapak
Version:        %{ver}~git%{date}.%{sub %{commit} 1 7}
Release:        %autorelease
Summary:        Run flatpak applications without installation

SourceLicense:  Apache-2.0
# FIXME: paste output of %%cargo_license_summary here
License:        # FIXME
# LICENSE.dependencies contains a full license breakdown

URL:            https://github.com/ryanabx/portapak

# To create this source:
# * git clone the repository
# * tar -pcJf $name-$commit.tar.xz
Source:         %{name}-%{commit}.tar.xz

BuildRequires:  cargo-rpm-macros >= 26
BuildRequires:  rustc
BuildRequires:  cargo

Requires:       flatpak

%global _description %{expand:
%{summary}.}

%description %{_description}

%prep
%autosetup -n %{name}-%{commit} -p1
%cargo_prep

%generate_buildrequires
%cargo_generate_buildrequires

%build
%cargo_build
%{cargo_license_summary}
%{cargo_license} > LICENSE.dependencies

%install
%cargo_install
install -Dm0644 data/net.ryanabx.Portapak.desktop %{_buildroot}/%{_datadir}/applications/net.ryanabx.Portapak.desktop

%if %{with check}
%check
%cargo_test
%endif

%files
%license LICENSE
%license LICENSE.dependencies
%doc README.md
%{_bindir}/portapak
%{_datadir}/applications/net.ryanabx.Portapak.desktop

%changelog
%autochangelog
