import { VerticalBox, HorizontalBox, Button, LineEdit, ProgressIndicator } from "std-widgets.slint";
export component MainWindow inherits Window {
    title: "Flatrun";
    icon: @image-url("../flatrun.png");
    callback start_job;
    in property <float> run_progress: 0.0;
    in property <string> current_action: "";
    in property <string> run_text: "";
    default-font-size: 10px;
    width: 640px;
    VerticalLayout {
        padding: 30px;
        alignment: center;
        spacing: 20px;
        VerticalLayout {
            alignment: center;
            spacing: 10px;
            Text {
                horizontal-alignment: center;
                text: "Flatrun";
                font-weight: 900;
                font-size: 32px;
            }

            Text {
                horizontal-alignment: center;
                wrap: TextWrap.word-wrap;
                font-italic: true;
                font-size: 12px;
                text: "Run flatpaks without installing...";
            }
        }

        HorizontalLayout {
            Text {
                horizontal-alignment: left;
                font-weight: 600;
                text: root.current_action;
            }

            Text {
                horizontal-alignment: right;
                font-weight: 600;
                text: root.run_text;
            }
        }

        ProgressIndicator {
            min-height: 20px;
            width: 100%;
            progress: root.run_progress;
        }
    }
}
